### PR TITLE
Handle alias mapping

### PR DESCRIPTION
**Pull request by briguy202**
This PR addresses https://github.com/asnowwolf/markup-inline-loader/issues/3 where the fix did not work in my testing.

I am new to webpack loaders, but it appears that the loader `resolve` method must be used to resolve alias mappings.  Unfortunately the sync version of the call `resolveSync` did not work for me and threw errors, so that led to some changes to support async operations.

### CODE REVIEW

**Comment by asnowwolf** [comment]
Thank you! 
can you show me an use case for the support of icons?

**Comment by briguy202** [comment]
We actually moved away from using the icons too, so I think that 743f873 can be ignored.

**Comment by asnowwolf** [comment]
so, could you please remove that commit and repush it?

**Comment by asnowwolf** [comment]
It is not a good idea to fix and refactor in a PR at the same time.
But it is a good idea to upgrade to es6, I have applied it to the master branch manually, please re-submit your changes based on the new master.

**Pull request closed without merging**
